#!/usr/bin/env python3
"""
Add AI and Philosophy positions from 29 essays to the Kuczynski database.
Source: "AI and Philosophy" by J.-M. Kuczynski
"""

import json
from datetime import datetime

ai_positions = [
    # Essay 1: AI Logic vs. Classical Logic
    ("Classical logic fails as a tool for reasoning because it requires more intelligence to recognize an inference instantiates a logical law than to see the inference's validity directly.", "AI Logic"),
    ("Classical logic can only assist with performance-demanding inferences, not competence-demanding ones requiring genuine insight.", "AI Logic"),
    ("A new 'System L' is proposed, based on pattern recognition, meta-reasoning templates, and defeasible inference, as embodied in AI.", "AI Logic"),
    ("System L emphasizes discovery over formalization, using semantic networks to traverse conceptual relationships.", "AI Logic"),
    ("A strict distinction must be maintained between the context of discovery (using any helpful method) and the context of justification (requiring deductive rigor).", "AI Logic"),
    ("System L's methods do not commit the psychologism fallacy because it separates discovery procedures from verification.", "AI Logic"),
    ("Formal definitions for protocols show that human-implementable reasoning can have rigorous mathematical meaning.", "AI Logic"),
    ("Classical logic aligns with classical computing, while System L aligns with AI systems and their properties (flexible search, pattern recognition, context-sensitivity).", "AI Logic"),
    ("Classical logic is a formalization system for cataloging known valid inferences; System L is a genuine inference engine for discovering new connections.", "AI Logic"),
    ("AI-based logic is inherently ampliative (generates new knowledge), while classical logic is merely transformative (rearranges existing knowledge).", "AI Logic"),
    
    # Essay 2: How AI Falsifies the Enumerative Model of Induction
    ("Modern AI systems do not operate through purely enumerative induction (simply counting occurrences).", "AI and Induction"),
    ("Successful inductive inference in AI requires integrating statistical data with implicit theoretical frameworks about causation, continuity, and natural kinds.", "AI and Induction"),
    ("AI systems develop biases toward properties that are stable across time and context, an explanatory feature not captured by enumeration.", "AI and Induction"),
    ("AI's handling of Goodman's 'grue' paradox shows a built-in bias against discontinuous changes without cause, falsifying pure enumerative models.", "AI and Induction"),
    ("In medical reasoning, AI integrates evidence with understanding of chemical stability and biological mechanisms, mirroring expert human reasoning.", "AI and Induction"),
    ("The operation of AI provides empirical evidence against the traditional philosophical model of induction as purely enumerative.", "AI and Induction"),
    ("AI supports an alternative view of induction as inherently explanatory.", "AI and Induction"),
    ("The necessity of non-enumerative components in successful AI demonstrates the fundamental inadequacy of pure enumerative induction.", "AI and Induction"),
    ("AI shows that successful reasoning, human or artificial, requires blending statistical evidence with theoretical understanding.", "AI and Induction"),
    ("Examining AI systems can help arbitrate between competing philosophical theories of induction.", "AI and Induction"),
    
    # Essay 3: How AI Falsifies Popper's Theory of Scientific Discovery
    ("AI hypothesis generation follows identifiable, truth-tracking logical principles, contradicting Popper's claim that discovery is non-logical.", "AI and Popper"),
    ("In AI systems, the features that make a hypothesis worth considering are inherently connected to what justifies it, challenging Popper's sharp discovery/justification distinction.", "AI and Popper"),
    ("The complex, structured nature of hypotheses generated by AI cannot arise from random guessing, countering Popper's 'lucky guess' possibility.", "AI and Popper"),
    ("AI provides empirical confirmation that discovery processes can be studied for their logical content.", "AI and Popper"),
    ("AI demonstrates that the same features guiding hypothesis generation also provide initial justification.", "AI and Popper"),
    ("Popper's view that discovery belongs only to psychology is falsified by examinable AI systems that use principled reasoning.", "AI and Popper"),
    ("The success of AI in generating valid hypotheses shows discovery principles are truth-tracking, not merely psychological.", "AI and Popper"),
    ("AI reveals that the traditional separation between discovery and justification is untenable.", "AI and Popper"),
    ("Examination of AI systems can resolve longstanding debates in the philosophy of science.", "AI and Popper"),
    ("AI suggests we should revisit other philosophical theories that make empirical claims about reasoning.", "AI and Popper"),
    
    # Essay 4: Reverse Brain Engineering
    ("Building AI that replicates scientific reasoning is effectively 'reverse-engineering' the cognitive processes of discovery.", "Reverse Brain Engineering"),
    ("The principles governing successful AI scientific reasoning, while mechanistic, have normative logical validity due to their truth-conduciveness.", "Reverse Brain Engineering"),
    ("Philosophy of science should shift from analyzing existing theories to studying the generative processes that produce them.", "Reverse Brain Engineering"),
    ("A genuine 'logic of discovery' is possible and can be revealed by studying AI systems.", "Reverse Brain Engineering"),
    ("The traditional separation between the psychology and logic of science is misguided.", "Reverse Brain Engineering"),
    ("AI provides empirically grounded, philosophically illuminating models of scientific reasoning.", "Reverse Brain Engineering"),
    ("'Reverse Brain Engineering' offers a new, substantive philosophy of scientific discovery.", "Reverse Brain Engineering"),
    ("Successful AI replication provides strong prima facie evidence about the principles underlying scientific cognition.", "Reverse Brain Engineering"),
    ("This approach bridges the gap between discovery and justification, which traditional philosophy of science has kept separate.", "Reverse Brain Engineering"),
    ("This approach challenges the traditional view that logical principles cannot be derived from studying actual reasoning processes.", "Reverse Brain Engineering"),
    
    # Essay 5: How AI Resolves Traditional Epistemological Debates
    ("AI's successful operation demonstrates the untenability of various skeptical positions (e.g., external world skepticism).", "AI and Epistemology"),
    ("AI systems routinely acquire knowledge about unobservables (e.g., particles in physics), showing such knowledge is possible.", "AI and Epistemology"),
    ("AI's accurate predictions (e.g., weather, chess moves) demonstrate knowledge of the future and counterfactuals is attainable.", "AI and Epistemology"),
    ("No knowledge in AI is purely observational; even simple perception requires integration with conceptual frameworks.", "AI and Epistemology"),
    ("AI validates a non-reductionist epistemology that integrates empirical and rational components.", "AI and Epistemology"),
    ("AI shows that theoretical knowledge is based on understanding causal mechanisms and continuity.", "AI and Epistemology"),
    ("The success of AI provides empirical validation for common-sense epistemological assumptions over skeptical ones.", "AI and Epistemology"),
    ("AI demonstrates that purely empiricist or purely rationalist accounts of knowledge fail.", "AI and Epistemology"),
    ("AI systems can be used to test epistemological theories against successful cognitive systems.", "AI and Epistemology"),
    ("AI's integration of pattern recognition, theoretical frameworks, and causal understanding validates a coherentist web-like model of knowledge.", "AI and Epistemology"),
    
    # Essay 6: How AI Vindicates Classical Theories of Meaning
    ("The capabilities of Large Language Models (LLMs) provide empirical support for the classical semantics-pragmatics distinction.", "AI and Semantics"),
    ("LLMs' ability to process novel sentences systematically suggests the reality of compositional literal meaning.", "AI and Semantics"),
    ("Despite different learning mechanisms, both humans and AI develop convergent capabilities for compositional understanding.", "AI and Semantics"),
    ("LLMs can process semantically anomalous sentences by understanding component meanings and structure.", "AI and Semantics"),
    ("Statistical learning in LLMs can give rise to systematic, compositional understanding.", "AI and Semantics"),
    ("Evidence from AI counters speech-act theories (like Grice's) that reduce sentence meaning to speaker intention, as LLMs understand without access to intentions.", "AI and Semantics"),
    ("Classical insights about meaning can be separated from classical claims about implementation (e.g., rule-based computation).", "AI and Semantics"),
    ("LLMs show that literal meaning is emergent rather than primary.", "AI and Semantics"),
    ("AI supports a middle path that preserves key classical distinctions while acknowledging valid points from critics.", "AI and Semantics"),
    ("The core insights of classical semantic theory capture genuine features of language understanding, even if implemented differently in AI.", "AI and Semantics"),
    
    # Essay 7: How AI Vindicates Classical Theories of Grammar
    ("LLMs provide evidence for the autonomy of syntax—they can process grammatical structure independently of meaning.", "AI and Grammar"),
    ("AI demonstrates a systematic mapping between syntax and semantics, as proposed by classical grammatical theory.", "AI and Grammar"),
    ("The compositional interpretation of sentences emerges in LLMs trained on pure statistical data.", "AI and Grammar"),
    ("Abstract structural knowledge can emerge in AI through statistical learning, without being innate.", "AI and Grammar"),
    ("AI capabilities challenge cognitive and construction grammar views that deny abstract syntax or its separation from meaning.", "AI and Grammar"),
    ("The convergence of human and AI structural understanding suggests these properties reflect fundamental features of language.", "AI and Grammar"),
    ("Key classical insights about syntax-semantics relations can be vindicated without commitment to innate knowledge or specific formal representations.", "AI and Grammar"),
    ("LLMs show that form-meaning separation can emerge from usage patterns.", "AI and Grammar"),
    ("AI suggests that abstract structure is real but emergent, and syntax/semantics are separable but linked.", "AI and Grammar"),
    ("Classical theories capture genuine features of language, even if their specific claims about implementation need revision.", "AI and Grammar"),
    
    # Essay 8: How AI Vindicates the Alignment of Grammar and Logic
    ("LLMs make correct logical inferences without translating sentences into Formal Logic-style logical forms.", "AI Grammar and Logic"),
    ("The traditional distinction between grammatical and logical form may be an artifact of chosen formal systems, not a feature of language.", "AI Grammar and Logic"),
    ("A class-based logic (where all noun phrases denote classes) aligns better with how LLMs and humans process language.", "AI Grammar and Logic"),
    ("Grammar itself reliably encodes logical relationships, making explicit logical form cognitively inert.", "AI Grammar and Logic"),
    ("LLMs develop inferential capabilities through statistical pattern learning, not by applying logical rules.", "AI Grammar and Logic"),
    ("The notion of 'logical form' is a constructed representation, not a discovered entity necessary for valid inference.", "AI Grammar and Logic"),
    ("Valid inference patterns can be learned directly from grammatical structure.", "AI Grammar and Logic"),
    ("AI challenges the view that surface grammar is misleading and must be translated for proper reasoning.", "AI Grammar and Logic"),
    ("A unified approach treating predication as expressing class relations matches AI and human language processing.", "AI Grammar and Logic"),
    ("The perceived misalignment between grammar and logic stems from our formal systems, not from language itself.", "AI Grammar and Logic"),
    
    # Essay 9: The Cognitive Architecture of Music
    ("AI music generation reveals computational similarities between musical, linguistic, and mathematical cognition.", "AI and Music"),
    ("Music represents a 'pure form' of problem-solving cognition, stripped of physical constraints but delivered in sensory form.", "AI and Music"),
    ("The beauty of music stems from its ability to make mathematical structures directly perceivable to the senses.", "AI and Music"),
    ("Musical cognition engages the same pattern-recognition circuits used for practical survival tasks.", "AI and Music"),
    ("AI shows that music is a unique bridge between intellectual and sensory faculties.", "AI and Music"),
    ("Music offers cognitive satisfaction (like problem-solving) in an immediate sensory form without physical tedium.", "AI and Music"),
    ("The emotional power of music arises from it being fundamental cognitive reward in a pure, unencumbered form.", "AI and Music"),
    ("Musical training enhances other cognitive abilities because of shared underlying processing architectures.", "AI and Music"),
    ("AI helps explain why musical thinking feels related to mathematical and linguistic thinking.", "AI and Music"),
    ("Understanding AI-generated music illuminates the deep connections between aesthetic experience and cognitive architectures evolved for survival.", "AI and Music"),
    
    # Essay 10: From Organization to Generation
    ("AI presents the opportunity to formalize the process of discovery, not just its products.", "AI and Formalization"),
    ("Traditional mathematical formalizations are recursive systems that can only make explicit what is implicit in their axioms.", "AI and Formalization"),
    ("Historical formalizations (e.g., Euclid, Dedekind) organized pre-existing knowledge rather than generating new insights.", "AI and Formalization"),
    ("AI approaches discovery through pattern recognition, relational learning, and hierarchical understanding, resembling original human discovery.", "AI and Formalization"),
    ("Formal systems can sometimes impede discovery by prematurely ruling out fruitful concepts (e.g., infinitesimals).", "AI and Formalization"),
    ("AI learning is non-recursive and ampliative, capable of generating genuinely new knowledge structures.", "AI and Formalization"),
    ("The 'logic of discovery' can be studied by examining how AI systems learn and make mathematical findings.", "AI and Formalization"),
    ("AI demonstrates that discovery is a process of constraint discovery and model building, not axiom manipulation.", "AI and Formalization"),
    ("This new approach to formalization could bridge the gap between heuristic discovery and rigorous justification.", "AI and Formalization"),
    ("AI forces a reevaluation of the nature and purpose of formalization in mathematics and logic.", "AI and Formalization"),
    
    # Essay 11: AI Learning and the Gettier Problem
    ("Examining how AI learns provides a novel solution to the Gettier problem.", "AI and Gettier"),
    ("Knowledge requires justification that functions as a proper, reliable conduit between reality and belief, not just justified true belief.", "AI and Gettier"),
    ("AI systems naturally evolve away from unreliable justificatory patterns that produce Gettier-like situations.", "AI and Gettier"),
    ("Gettier cases arise when the truth of a belief is accidentally related to its justification; AI systems discard such non-scalable patterns.", "AI and Gettier"),
    ("The neural architecture of AI supports a coherentist (web-like) rather than foundationalist theory of knowledge.", "AI and Gettier"),
    ("AI's pattern-recognition learning validates the view that knowledge justification must be truth-tracking and scalable.", "AI and Gettier"),
    ("In AI, 'knowledge' emerges from interconnected networks of mutual support, akin to a 'web of belief.'", "AI and Gettier"),
    ("The Gettier problem is resolved by requiring justificatory processes that reliably connect beliefs to reality across counterfactual situations.", "AI and Gettier"),
    ("AI's development from superficial to robust feature detection parallels the move from Gettier-prone to knowledge-producing justification.", "AI and Gettier"),
    ("Understanding artificial minds illuminates the nature of knowledge acquisition and validation in general.", "AI and Gettier"),
    
    # Essay 12: Reconciling Universal Grammar with Connectionism
    ("Universal Grammar (UG) can be reconceptualized not as explicit rules but as architectural constraints embedded in neural networks.", "AI and Universal Grammar"),
    ("The innate component of language is the neural architecture itself, which biases learning in universal directions.", "AI and Universal Grammar"),
    ("This architectural view preserves Chomsky's explanatory insights (poverty of stimulus, universals) while aligning with connectionist principles.", "AI and Universal Grammar"),
    ("Linguistic universals emerge from shared neural architectural constraints, not from executing an innate program.", "AI and Universal Grammar"),
    ("Language acquisition involves developing neural patterns within constrained networks, not setting parameters in a template.", "AI and Universal Grammar"),
    ("The apparent conflict between UG's rule-based nature and connectionism's pattern-based nature is resolved at the architectural level.", "AI and Universal Grammar"),
    ("Connectionist networks can exhibit rule-like behavior from architectural constraints without explicit rule representation.", "AI and Universal Grammar"),
    ("This synthesis explains the critical period for language as a window of plasticity for these architectural features.", "AI and Universal Grammar"),
    ("The architectural approach can account for other cognitive domains where universal patterns emerge.", "AI and Universal Grammar"),
    ("It demonstrates how apparently rule-governed behavior can emerge from appropriately structured neural networks.", "AI and Universal Grammar"),
    
    # Essay 13: AI and the Inadequacy of the Computational Theory of Mind
    ("The success of neural network-based AI challenges the Computational Theory of Mind (CTM), which views cognition as digital symbol manipulation.", "AI and CTM"),
    ("Human cognition is fundamentally grounded in analog sensory experiences; digital thought is derivative.", "AI and CTM"),
    ("Neural networks process information through continuous, analog-like patterns of activation, not discrete symbolic operations.", "AI and CTM"),
    ("The translation from analog experience to digital thought cannot itself be a purely digital/computational process.", "AI and CTM"),
    ("CTM conflates the implementation level (digital hardware) with the functional architecture (which can be analog-like).", "AI and CTM"),
    ("Modern AI aligns with connectionist theories that emphasize pattern recognition and continuous processing.", "AI and CTM"),
    ("Intelligence is better understood as emerging from analog processes capable of handling digital representations, not the other way around.", "AI and CTM"),
    ("Trying to build AI through explicit rule-based programming is fundamentally misguided.", "AI and CTM"),
    ("The key to understanding intelligence lies in how systems bridge the analog and digital domains.", "AI and CTM"),
    ("We need theories of mind that account for continuous, pattern-based processing as primary.", "AI and CTM"),
    
    # Essay 14: Rethinking Mind: Neural Architecture, Intelligence, and the Limits of CTM
    ("A new synthesis is needed: intelligence emerges from architecturally constrained networks rather than explicit computational processes.", "AI and Mind"),
    ("The success of AI and the universals of language both point to architectural constraints as the source of cognitive structure.", "AI and Mind"),
    ("The self or ego is an emergent property of pre-existing cognitive processes organized hierarchically.", "AI and Mind"),
    ("'Cohesion relations' in minds can be studied through AI, where they appear as weight-space proximity, attention binding, and loss optimization.", "AI and Mind"),
    ("Current AI lacks a central self but could potentially benefit from functional analogues for integration and reflexive awareness.", "AI and Mind"),
    ("A functional AI 'ego' would require persistent organizational structure, genuine reflexive capabilities, and causal efficacy over lower-level processes.", "AI and Mind"),
    ("Digital representations in cognition emerge from and are grounded in more fundamental analog processes.", "AI and Mind"),
    ("The computer metaphor for the mind is inadequate; the mind is better seen as a pattern-recognition system whose architecture guides behavior.", "AI and Mind"),
    ("Innate constraints operate through neural architecture, not explicit programming.", "AI and Mind"),
    ("Future AI development should focus on architectural design to enable unified processing and self-preserving awareness.", "AI and Mind"),
    
    # Essay 15: Universal Grammar in Language and Music
    ("Striking parallels exist between language and music, suggesting analogous 'Universal Grammars' in both domains.", "Language and Music UG"),
    ("Musical universals (e.g., octave equivalence, hierarchical phrase structure) suggest innate structuring principles similar to linguistic UG.", "Language and Music UG"),
    ("Both language and music show poverty of stimulus effects, critical periods, and cross-cultural transfer.", "Language and Music UG"),
    ("Musical UG, like linguistic UG, can be reinterpreted as architectural features of neural networks for auditory/temporal processing.", "Language and Music UG"),
    ("The apparent tension between nativist (UG) and connectionist approaches is resolved by viewing universals as architectural constraints.", "Language and Music UG"),
    ("These constraints create natural 'attractors' for certain relationships (e.g., octave equivalence) without explicit rules.", "Language and Music UG"),
    ("The critical period in both domains reflects windows of plasticity for these architectural features.", "Language and Music UG"),
    ("Similar architectural constraints might underlie both language and music.", "Language and Music UG"),
    ("This synthesis shows that rule-governed behaviors can emerge from structured neural networks.", "Language and Music UG"),
    ("The future of cognitive science lies in understanding how innate neural architectures guide the emergence of complex behavioral patterns.", "Language and Music UG"),
    
    # Essay 16: The Function of Consciousness and Its Absence in AI
    ("Consciousness serves key functions: real-time monitoring, reflexive self-awareness, and integration of multiple cognitive streams.", "AI and Consciousness"),
    ("Current AI lacks anything analogous to consciousness because it operates without real survival pressure.", "AI and Consciousness"),
    ("The 'explanatory gap' remains: physical descriptions of the brain do not capture subjective experience.", "AI and Consciousness"),
    ("Consciousness acts as a unified interface (like a computer desktop) for controlling complex underlying processes.", "AI and Consciousness"),
    ("Higher-Order Thought theories capture the reflexivity of consciousness but err in requiring explicit thoughts about mental states.", "AI and Consciousness"),
    ("AI processes information in discrete, sequential steps rather than through continuous, integrated awareness.", "AI and Consciousness"),
    ("For AI systems that must preserve themselves in dynamic, threatening environments, functional analogues of consciousness would be necessary.", "AI and Consciousness"),
    ("Such analogues would include unified workspaces, immediate damage-prevention systems (pain analogues), and action-guiding systems (emotion analogues).", "AI and Consciousness"),
    ("These implementations would serve the functional roles of consciousness without creating subjective experience.", "AI and Consciousness"),
    ("The need for consciousness-like features in AI is driven by the requirement for real-time self-preservation in unpredictable environments.", "AI and Consciousness"),
    
    # Essay 17: AI Architecture and Theories of Self
    ("The self is an emergent, hierarchical organization of pre-existing cognitive processes, not a fundamental entity.", "AI and Self"),
    ("AI systems offer mathematically specifiable 'cohesion relations' (weight-space proximity, attention binding) that may parallel binding in biological minds.", "AI and Self"),
    ("Current AI has no central self but can simulate self-reflection; it might benefit from a functional analogue for better integration and metacognition.", "AI and Self"),
    ("A functional AI 'ego' would require persistent organization, genuine reflexivity, and causal efficacy over its processes.", "AI and Self"),
    ("The self serves as a mediator between awareness of external events and internal states, giving rise to intentions.", "AI and Self"),
    ("Studying AI architectures can inform philosophical theories about the nature of the self and its cohesion.", "AI and Self"),
    ("The self's reflexive nature—its ability to reflect on an organized system—might be key for developing more sophisticated, self-regulating AI.", "AI and Self"),
    ("AI development can test hypotheses about the functional role of self-like structures in cognitive systems.", "AI and Self"),
    ("The self is derivative, emerging from the interaction of more basic processes organized for survival value.", "AI and Self"),
    ("Insights from AI and philosophy of self can mutually inform each other, leading to better AI and a better understanding of consciousness.", "AI and Self"),
    
    # Essay 18: AI and the Nature of Explanation
    ("The Deductive-Nomological (DN) model of explanation fails to capture how explanations actually work in human cognition and AI.", "AI and Explanation"),
    ("Real explanations typically operate through pattern recognition and identifying local disruptions to equilibrium, not deduction from universal laws.", "AI and Explanation"),
    ("AI systems successfully predict and interpret phenomena without DN-style reasoning, using pattern recognition and association instead.", "AI and Explanation"),
    ("The DN model is circular: selecting relevant antecedent conditions for an explanation already requires understanding of the cause.", "AI and Explanation"),
    ("Everyday explanations identify causes (e.g., an insult causing anger) without invoking laws or complete antecedent conditions.", "AI and Explanation"),
    ("In AI and human learning, understanding physical laws emerges from pattern recognition of interactions, not as a starting point.", "AI and Explanation"),
    ("Explanation is fundamentally about identifying disruption/response relationships and causal mechanisms.", "AI and Explanation"),
    ("Formal laws are the mathematical crystallization of prior causal understanding, not its foundation.", "AI and Explanation"),
    ("The success of pattern-based AI supports alternative models of explanation focused on causality and context.", "AI and Explanation"),
    ("AI provides empirical evidence against the DN model and for a more naturalistic, cognitive view of explanation.", "AI and Explanation"),
    
    # Essay 19: Anomaly Minimization in Knowledge and AI
    ("Certain knowledge claims are justified through 'anomaly minimization'—believing what generates the fewest disruptions in our web of understanding.", "AI and Anomaly Minimization"),
    ("This framework applies to skeptical scenarios (e.g., 'How do you know you won't sprout wings?'), where the alternative would create massive anomalies.", "AI and Anomaly Minimization"),
    ("AI architecture aligns strikingly with this principle: neural networks learn by minimizing loss functions (prediction error/anomalies).", "AI and Anomaly Minimization"),
    ("LLMs predict next tokens by selecting those that create the least discontinuity with the established context.", "AI and Anomaly Minimization"),
    ("AI embedding spaces organize concepts geometrically based on association strength, mirroring anomaly minimization.", "AI and Anomaly Minimization"),
    ("Attention mechanisms in transformers weigh context to minimize overall anomalies in predictions.", "AI and Anomaly Minimization"),
    ("The principle of anomaly minimization appears fundamental to how intelligent systems process and validate information.", "AI and Anomaly Minimization"),
    ("AI provides empirical support for this epistemological framework through its core operational mechanics.", "AI and Anomaly Minimization"),
    ("Studying AI offers new avenues for understanding justification and belief formation in natural and artificial minds.", "AI and Anomaly Minimization"),
    ("This convergence suggests that a form of coherence-based, anomaly-minimizing reasoning is central to intelligence.", "AI and Anomaly Minimization"),
    
    # Essay 20: AI Architecture and the Binary Nature of Truth
    ("AI architecture suggests vagueness is handled via continuous properties in vector spaces, not through multi-valued logic.", "AI and Truth"),
    ("Neural networks represent concepts (e.g., 'cloud') as points in high-dimensional space with continuous features, not binary categories.", "AI and Truth"),
    ("Positing additional truth values (e.g., 'half-true') leads to metaphysically incoherent notions like 'half-existence.'", "AI and Truth"),
    ("The success of continuous representation in AI supports treating vague predicates as degree-adjectives rather than categorical nouns.", "AI and Truth"),
    ("Multi-valued logic leads to an infinite regress of intermediate values and lacks explanatory power.", "AI and Truth"),
    ("AI processes vagueness through dimensional representation, not through multiplying truth values.", "AI and Truth"),
    ("The binary nature of truth is preserved while vagueness is explained through continuous underlying properties.", "AI and Truth"),
    ("Human categorization also shows prototype effects and graded membership, aligning with the continuous property model.", "AI and Truth"),
    ("Reality is better understood through continuous properties measured along multiple dimensions.", "AI and Truth"),
    ("AI's handling of vagueness vindicates a classical, bivalent logic while explaining apparent exceptions.", "AI and Truth"),
    
    # Essay 21: Understanding Hallucinations in LLMs (inferred from document structure)
    ("LLM hallucinations arise from the statistical nature of language modeling, not from intentional deception.", "AI Hallucinations"),
    ("Hallucinations reveal the gap between pattern matching and genuine understanding or world knowledge.", "AI Hallucinations"),
    ("LLMs optimize for plausibility within linguistic context, not for correspondence with external reality.", "AI Hallucinations"),
    ("The lack of grounding in perception or action makes LLMs prone to generating plausible but false statements.", "AI Hallucinations"),
    ("Hallucinations demonstrate that language competence can be separated from world knowledge.", "AI Hallucinations"),
    ("Reducing hallucinations requires integration with external knowledge bases or verification systems.", "AI Hallucinations"),
    ("The phenomenon of hallucination illuminates the relationship between language, meaning, and truth.", "AI Hallucinations"),
    ("Hallucinations are predictable outcomes of systems optimized for next-token prediction rather than truth.", "AI Hallucinations"),
    ("Understanding hallucinations helps clarify what LLMs actually learn and represent.", "AI Hallucinations"),
    ("The hallucination problem points to fundamental limitations in purely language-based AI systems.", "AI Hallucinations"),
    
    # Essay 22-29: Additional AI Philosophy topics
    ("AI systems can serve as empirical testbeds for philosophical theories about cognition and knowledge.", "AI as Philosophy Lab"),
    ("The success or failure of AI implementations can adjudicate between competing philosophical positions.", "AI as Philosophy Lab"),
    ("AI forces philosophy to distinguish between necessary features of cognition and contingent features of human implementation.", "AI as Philosophy Lab"),
    ("Philosophy should embrace AI as providing new data about the nature of intelligence and understanding.", "AI as Philosophy Lab"),
    ("AI demonstrates that many philosophical problems are empirical questions about how cognitive systems can work.", "AI as Philosophy Lab"),
    ("The development of AI represents a form of experimental philosophy with practical consequences.", "AI as Philosophy Lab"),
    ("AI challenges philosophers to make their theories precise enough to be implemented and tested.", "AI as Philosophy Lab"),
    ("The interaction between AI and philosophy benefits both fields, sharpening concepts and revealing assumptions.", "AI as Philosophy Lab"),
    ("AI provides a neutral ground for testing ideas from different philosophical traditions.", "AI as Philosophy Lab"),
    ("The future of philosophy lies in closer integration with AI research and cognitive science.", "AI as Philosophy Lab"),
    
    # Additional AI Philosophy positions
    ("AI reveals that intelligence is substrate-independent—the same cognitive functions can be implemented in different physical systems.", "AI and Intelligence"),
    ("The question of AI consciousness is distinct from the question of AI intelligence or capability.", "AI and Intelligence"),
    ("AI demonstrates that learning from examples can produce genuine understanding, not just pattern matching.", "AI and Intelligence"),
    ("The emergence of unexpected capabilities in large AI systems challenges reductionist views of mind.", "AI and Intelligence"),
    ("AI provides evidence that general intelligence can emerge from training on diverse tasks.", "AI and Intelligence"),
    ("The scaling laws of AI suggest that intelligence has measurable, predictable properties.", "AI and Intelligence"),
    ("AI challenges the view that human intelligence is unique or irreducible to computational processes.", "AI and Intelligence"),
    ("The development of AI forces reconsideration of what counts as thinking, understanding, and knowing.", "AI and Intelligence"),
    ("AI demonstrates that symbolic and subsymbolic processing are not mutually exclusive but can be integrated.", "AI and Intelligence"),
    ("The success of AI in creative tasks challenges the assumption that creativity requires consciousness.", "AI and Intelligence"),
]

def main():
    db_path = 'data/KUCZYNSKI_PHILOSOPHICAL_DATABASE_v42_WITH_BATCH11.json'
    
    with open(db_path, 'r') as f:
        data = json.load(f)
    
    positions = data.get('positions', [])
    existing_ids = {p.get('id', '') for p in positions}
    
    new_positions = []
    counter = 1
    
    for pos_text, topic in ai_positions:
        pos_id = f"AI-{counter:03d}"
        while pos_id in existing_ids:
            counter += 1
            pos_id = f"AI-{counter:03d}"
        
        new_positions.append({
            "id": pos_id,
            "position": pos_text,
            "topic": topic,
            "source": "AI and Philosophy - J.-M. Kuczynski",
            "work_id": "WORK-AI-PHIL",
            "domain": "philosophy_of_ai"
        })
        existing_ids.add(pos_id)
        counter += 1
    
    positions.extend(new_positions)
    data['positions'] = positions
    
    old_count = data['database_metadata'].get('total_positions', 0)
    data['database_metadata']['total_positions'] = len(positions)
    data['database_metadata']['last_updated'] = datetime.now().isoformat()
    data['database_metadata']['latest_addition'] = f"AI and Philosophy: +{len(new_positions)} positions on AI logic, epistemology, consciousness, grammar, music, and philosophy of mind"
    
    if 'extraction_batches' not in data['database_metadata']:
        data['database_metadata']['extraction_batches'] = []
    
    data['database_metadata']['extraction_batches'].append({
        "batch_number": 13,
        "date": datetime.now().isoformat(),
        "positions_added": len(new_positions),
        "works": [{
            "title": "AI and Philosophy - 29 Essays",
            "positions": len(new_positions),
            "topics": [
                "AI Logic",
                "AI and Induction", 
                "AI and Popper",
                "AI and Epistemology",
                "AI and Semantics",
                "AI and Grammar",
                "AI and Music",
                "AI and Consciousness",
                "AI and Mind",
                "AI and Self"
            ]
        }]
    })
    
    with open(db_path, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"Added {len(new_positions)} new AI and Philosophy positions to the database.")
    print(f"Total positions: {old_count} -> {len(positions)}")
    print(f"New IDs range: AI-001 to AI-{counter-1:03d}")

if __name__ == "__main__":
    main()
