#!/usr/bin/env python3
"""Generate Bergler fact positions (quotes) file"""

import json

QUOTES = [
    ("The pre-Oedipal oral phase (0-18 months) is more fundamental to neurosis than the Oedipal phase (3-5 years).", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("There is only one 'basic neurosis'—repressed masochistic attachment to the fantasied earliest 'bad mother.'", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Psychic masochism is the unconscious pursuit of 'pleasure in displeasure.'", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Psychic masochism constitutes 'the life-blood of neurosis' and is in fact the basic neurosis.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Neurotic equals psychic masochist—every neurotic is fundamentally a psychic masochist.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("The superego is the 'real master of the personality.'", "THE SUPEREGO", "superego_theory"),
    ("The superego operates as 'torture for torture's sake.'", "THE SUPEREGO", "superego_theory"),
    ("The punitive part of the superego (Daimonion) uses the ego ideal to torture the ego.", "THE SUPEREGO", "superego_theory"),
    ("Punishment itself becomes masochized—the neurotic derives unconscious pleasure from being punished.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Infantile megalomania and infantile omnipotence are of prime importance in the reduction of anxiety.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Man's inhumanity to man is equaled only by man's inhumanity to himself.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("People are heavily defended against realization of the darkest aspects of human nature—their emotional addiction to unresolved negative emotions.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("The infant's first important emotional relationship is with the mother (breast/bottle) during the oral stage.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Later neuroses 'reformulating' oral masochistic material represent 'rescue stations.'", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("Neurotics cling to and repeat misery, which in itself indicates psychic masochism.", "THE BASIC NEUROSIS", "foundational_metapsychology"),
    ("The 'mechanism of orality' is paradigmatic for the masochistic character.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("The mechanism of orality consists of a three-act triad operating unconsciously.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Act 1: Through provocative behavior, a situation is brought about in which some substitute of the pre-Oedipal mother is 'refusing.'", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Act 2: Not realizing they manufacture disappointment, neurotics become aggressive in 'righteous indignation' and seemingly in self-defense.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Act 3: They indulge in endless self-pity, unconsciously enjoying psychic masochism.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Neurotics repress completely the fact of their own initial provocation that began the sequence.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Neurotics repress the masochistic enjoyment of self-pity.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("The ego-strengthening illusion of 'aggression' is maintained while the decisive masochistic substructure remains hidden.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Psychic masochism unconsciously 'sugarcoats' and 'neutralizes' pain.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Consciously, pain remains and is felt in symptoms and personality distortions.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Psychic masochists unconsciously want refusal, rejection, humiliation, and defeat.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("The genuine 'wish to get' of infancy is now a defense in the adult neurotic.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Those who operate by the mechanism of orality are 'injustice collectors.'", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("A person who unconsciously runs after disappointment cannot be consciously happy.", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Neurotics cast others as the 'bad, refusing mother.'", "THE BASIC NEUROSIS", "mechanism_of_orality"),
    ("Neurotic symptoms and traits have a five-layer structure.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("Psychic masochism is disguised from the superego by two defensive alibis.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("In the normal person, the fifth layer is antimasochistic.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("In neurosis, the final layer 'smuggles in' masochism in self-damaging symptoms.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("Neurotics cannot be helped unless their psychic masochism is analyzed.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("Every clinical entity incorporates a unique 'specific additional factor' on top of the basic mechanism.", "THE BASIC NEUROSIS", "neurotic_symptom_structure"),
    ("Neurotics shift the blame outside, mostly to parents—this is the 'basic fallacy.'", "THE BASIC NEUROSIS", "basic_fallacy"),
    ("The basic fallacy must be shown to be a fallacy for treatment to succeed.", "THE BASIC NEUROSIS", "basic_fallacy"),
    ("All neurotic aggression is 'pseudoaggression.'", "THE BASIC NEUROSIS", "pseudoaggression"),
    ("Pseudoaggression promotes self-damage rather than genuine assertion.", "THE BASIC NEUROSIS", "pseudoaggression"),
    ("Neurotic aggression serves masochistic purposes while appearing defensive.", "THE BASIC NEUROSIS", "pseudoaggression"),
    ("The neurotic believes he is fighting back when in fact he is engineering his own defeat.", "THE BASIC NEUROSIS", "pseudoaggression"),
    ("The superego requires constant appeasement.", "THE SUPEREGO", "superego_theory"),
    ("Psychic masochism constitutes the most dangerous countermeasure of the unconscious ego against the superego's tyranny.", "THE SUPEREGO", "superego_theory"),
    ("Inner guilt drives repetitive self-damaging behavior.", "THE SUPEREGO", "superego_theory"),
    ("The 'inner conscience' (superego) constantly accuses the ego.", "THE SUPEREGO", "superego_theory"),
    ("The unconscious ego defends against superego reproaches through various mechanisms.", "THE SUPEREGO", "superego_theory"),
    ("When superego attacks are mild ('raids'), neurotic symptoms may be transitory.", "THE SUPEREGO", "superego_theory"),
    ("Neurotic symptoms have a 'pseudo-moral connotation'—ironization of teachings to prop up each symptom.", "THE SUPEREGO", "superego_theory"),
    ("The battle of the conscience is the central drama of neurotic life.", "THE SUPEREGO", "superego_theory"),
    ("Writer's block is a clinical condition rooted in oral masochism.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("Writer's block was coined as a term in 1947.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("Writers are fortunate in that they are able to treat their neurosis every day by writing.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("As soon as the writer is blocked, this is catastrophic because the writer will start to go to pieces.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("Many a person cannot bear the thought of being completely controlled by the unconscious.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("The productive writer eliminates, intrapsychically, the mother—autarchically giving himself ideas and words (milk).", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("The successful writer sets a 'magic gesture' into motion—dramatizing how he allegedly wanted to be treated.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("The unproductive, neurotically inhibited writer exhausts his psychic energy in the creation of his unconscious alibi of pseudo-aggression ('I refuse').", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("The inhibited writer retains the unconscious masochistic wish to be refused.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("When the writer cannot convince his superego of the 'harmlessness' of his imagination, he has no ideas at all.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("If the writer clears the imagination hurdle but cannot obtain approval of his exhibitionism in 'writing it down,' he cannot write.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("Creative writing involves unconscious autarchic provision of maternal nurturance to oneself.", "THE WRITER AND PSYCHOANALYSIS", "creativity"),
    ("All gamblers gamble because of psychic masochism.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("The gambler has an unconscious wish to lose.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Losing is necessary to establish the cruelty of fate for the gambler.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Gambling involves the re-creation of the infantile conflict with the refusing mother.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("The mysterious thrill in gambling is connected to unconscious masochistic enjoyment.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Gamblers experience a feeling of uncanniness connected to omnipotence fantasies.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("There is inner identity between games of 'chance' and games of 'reasoning.'", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Speculators (big and small) operate on similar psychological dynamics as other gamblers.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("There exists a typology of gamblers based on their specific masochistic configurations.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Pathological gambling shows clinical complexity involving multiple neurotic layers.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Superstition and systems in gambling serve defensive functions.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Gambling is objectively a losing proposition that satisfies masochistic needs.", "PSYCHOLOGY OF GAMBLING", "gambling"),
    ("Divorce is only a neurotic solution applied to neurotic persons.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("Changing the external factors of one's marriage cannot alter the inner conflict.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("Unhappy marriages result from neurotic mate selection based on the mechanism of orality.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("Neurotic marriages involve partners unconsciously seeking to repeat infantile conflicts.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("Tender love has unconscious connotations that are completely disregarded by purely biological approaches.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Frigidity in women is a manifestation of oral masochistic regression.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Psychic impotence in men is rooted in pre-Oedipal conflicts.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Premature ejaculation is the most frequent form of psychogenic potency disturbance.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Vaginal orgasm exists contrary to Kinsey's denial.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("'Counterfeit-sex' describes sexual behaviors that are neurotic substitutes for genuine sexuality.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Neurotic women often choose termagants (difficult partners) to repeat masochistic patterns.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("The 'allure of the forbidden' operates in neurotic sexual patterns.", "COUNTERFEIT-SEX", "marriage_sexuality"),
    ("Romantic love and sexual love have distinct psychoanalytic meanings.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("Monogamy and its difficulties reflect underlying oral conflicts.", "UNHAPPY MARRIAGE AND DIVORCE", "marriage_sexuality"),
    ("The revolt of the middle-aged man is a specific clinical syndrome.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("Middle-age rebellion originates in unresolved oral conflicts reactivated at midlife.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("The middle-aged rebel unconsciously seeks to recreate infantile disappointments.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("The rebel's wife plays a role in the masochistic drama.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("Children serve as judges in the middle-age revolt scenario.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("Resignation is not the way out of the middle-age crisis.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("The 'second adolescence' of middle age is a defensive configuration.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("Depressed mood in middle age relates to masochistic patterns.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("The ménage à trois fantasy often emerges in middle-age revolt.", "THE REVOLT OF THE MIDDLE-AGED MAN", "middle_age"),
    ("Injustice collectors are unconscious masochists who nurse resentments.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("Injustice collectors unconsciously provoke the very mistreatment they complain about.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("The injustice collector maintains an enormous cache of grievances going back years.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("Injustice collectors unconsciously enjoy self-pity.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("Injustice collectors believe they want normal pleasure but run after disappointment.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("The injustice collector's versions of events are often skewed or completely misinterpreted.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("Injustice collecting serves to validate the masochistic attachment to the bad mother.", "THE BASIC NEUROSIS", "injustice_collectors"),
    ("Boredom ('alysosis') is a neurotic disease, not merely a mood state.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Boredom is closely associated in a triad with scopophilia (voyeurism) and psychic masochism.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Boredom represents an unsuccessful defense mechanism against inner conscience reproaches.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("The prognosis is unfavorable in untreated boredom, which may result in suicide.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Boredom is progressive and never self-limited.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Erythrophobia (pathological blushing) is a manifestation of oral regression.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Logorrhoea (compulsive talking) serves defensive functions against masochistic guilt.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Kleptomania involves the mechanism of orality.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("The impostor syndrome has oral masochistic roots.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Hypocrisy has specific implications in neurosis and criminal psychopathology.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Cynicism is a mechanism deducible from oral masochistic theory.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("'Criminosis' describes criminal behavior rooted in masochistic self-damage.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("There exist 22 distinct visual neuroses.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Psychogenic aspermia (inability to ejaculate) has oral masochistic origins.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Alcoholism is treatable as an oral regression condition.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Hypochondria serves masochistic defensive purposes.", "CURABLE AND INCURABLE NEUROTICS", "neurotic_conditions"),
    ("Fashion involves unconscious motivations related to fear and defense.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Clothes are a masculine invention despite being associated with women.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Fashion contains paradoxes and contradictions of the 'improved skin.'", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("There are seven ingredients of haute couture related to unconscious dynamics.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Dresses relate to three types of reputation.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Clothes, children of man's fear, become independent cultural phenomena.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Some women have 'sartorial anti-talents' based on unconscious conflicts.", "FASHION AND THE UNCONSCIOUS", "culture"),
    ("Laughter and the sense of humor have specific psychoanalytic meanings.", "LAUGHTER AND THE SENSE OF HUMOR", "humor"),
    ("Humor involves complex dynamics of aggression and masochism.", "LAUGHTER AND THE SENSE OF HUMOR", "humor"),
    ("The psychology of humor relates to superego dynamics.", "LAUGHTER AND THE SENSE OF HUMOR", "humor"),
    ("Therapists should talk at length to patients to counteract their projection of 'bad refusing mother.'", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("More active analyzing is needed to unearth and interpret all repressed masochistic data.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("Repetitions must be identified and interpreted systematically.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("The transference relationship involves projection of the bad mother onto the analyst.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("Working through requires addressing the basic masochistic attachment.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("Neurotics who want to change can be cured; those who don't remain 'incurable.'", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("There are curable and incurable neurotics based on their willingness to analyze psychic masochism.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("'Malignant' psychic masochism differs from ordinary neurotic masochism.", "CURABLE AND INCURABLE NEUROTICS", "clinical_technique"),
    ("Parents are not guilty of their children's neuroses in the simple causal way commonly believed.", "PARENTS NOT GUILTY", "parents_children"),
    ("The child's subjective interpretation of maternal behavior creates the 'bad mother' imago.", "PARENTS NOT GUILTY", "parents_children"),
    ("The fantasied bad mother may differ substantially from the actual mother's behavior.", "PARENTS NOT GUILTY", "parents_children"),
    ("Children's neuroses involve the same oral masochistic dynamics as adult neuroses.", "PARENTS NOT GUILTY", "parents_children"),
    ("Kinsey's research avoids with 100 percent completeness any concession to the existence of the dynamic unconscious.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("The Kinsey scale is based on flawed assumptions.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("Kinsey's biological one-sidedness ignores psychodynamic factors.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("The 'taxonomic approach' fails to recognize the unconscious dimension of human sexuality.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("Kinsey's dismissal of premature ejaculation as a disorder is unjustified.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("Early puberty is an antedated defense expressed organically, not merely biological.", "COUNTERFEIT-SEX", "critique_of_kinsey"),
    ("Derogatory remarks about Freudian psychoanalysis are mainly based on ignorance or resistance, or both.", "THE BASIC NEUROSIS", "general_theoretical"),
    ("The oral phase is the most determining factor in the development of multiple psychological conditions, extending Freud's later insights about pre-Oedipal development.", "THE BASIC NEUROSIS", "general_theoretical"),
]

def main():
    quotes_data = []
    for quote, source, topic in QUOTES:
        quotes_data.append({
            "quote": quote,
            "source": source,
            "topic": topic
        })
    
    with open('data/bergler_fact_positions.json', 'w') as f:
        json.dump(quotes_data, f, indent=2)
    
    print(f"Created bergler_fact_positions.json with {len(quotes_data)} quotes")

if __name__ == '__main__':
    main()
